### ISSUE TITLE
Filesystem on server almost full

### ISSUE THREAD

**Issue by haakon-soegnen** [FNLF/fnlf-backend#51]
/dev/sda1          29496 27092      1168  96% /

**Comment by haakon-soegnen** [comment]
Production db is already 1.95GB. This means every observation on average uses 10mb

**Comment by einarhuseby** [comment]
Db is increasing fast due to media storage. Need to look into solutions for mongo storage.

**Comment by einarhuseby** [comment]
We have a 133GB "temporary disk"...

**Comment by einarhuseby** [comment]
Moved permanently to new server
