### ISSUE TITLE
Eve-docs not compatible with python 3.4

### ISSUE THREAD

**Issue by hakon-sognen** [FNLF/fnlf-backend#52]
Line 11 in config.py uses pre 3.0 print statement

**Comment by einarhuseby** [comment]
Should use https://github.com/einarhuseby/eve-docs.git@develop until eve-docs accepts pr's

See #54

**Comment by einarhuseby** [comment]
Switched to eve-swagger in 0.4.2-dev

**Comment by einarhuseby** [comment]
Changed to swagger #95
